Kubuntu jammy
marcosfad/mbp-ubuntu pull request #91
Opened 2023-06-19 20:27 UTC by lemmyg

Added kubuntu for jammy

2023-06-19 20:38 UTC, lemmyg commented on 02_build_image.sh
> -#define DISKNAME  Ubuntu MBP 22.04 LTS "Jammy Jellyfish" - Beta amd64
why beta?

2023-06-20 00:47 UTC, AdityaGarg8 commented on 02_build_image.sh
> -#define DISKNAME  Ubuntu MBP 22.04 LTS "Jammy Jellyfish" - Beta amd64
I had to change it, you may remove beta

2023-06-20 00:50 UTC, AdityaGarg8 requested changes
You also need to change grub.cfg

2023-06-20 07:01 UTC, AdityaGarg8 approved these changes

2023-06-20 07:05 UTC, merged